### ISSUE TITLE
Schedule and slots

### ISSUE THREAD

**Issue by pabluk** [sre-summercamp/sre-summercamp.github.io#10]
All the slots for the schedule were created following the [hackmd.io page](https://hackmd.io/dq5kUL5eQi-sbzKjv5FpfQ?view#Detailed-schedule) and it's now available at:

* https://sre-summercamp.github.io/schedule/#day_2022-09-03
* https://sre-summercamp.github.io/schedule/#day_2022-09-04

In order to add the content for every slot, these files need to be edited:
```
content/sessions/
├── activity_1.md
├── activity_2.md
├── activity_3.md
├── activity_4.md
├── keynote_open.md
├── talk_1.md
├── talk_2.md
├── talk_3.md
├── talk_4.md
├── talk_5.md
├── talk_6.md
├── talk_7.md
└── talk_8.md
```

**Comment by tormath1** [comment]
Ok - we can fill that along the CFP proposals. what do you think about clearing this `sessions` folder to avoid any confusions ? Or having a generic activity and a generic talk "TBD".

**Comment by pabluk** [comment]
> Ok - we can fill that along the CFP proposals. what do you think about clearing this `sessions` folder to avoid any confusions ? Or having a generic activity and a generic talk "TBD".

Yep, totally agree, we can fill out all the sessions with "TBD" as title :+1:

**Comment by tormath1** [comment]
Closed via: https://github.com/sre-summercamp/sre-summercamp.github.io/pull/23
