### ISSUE TITLE
light theme: red background is pretty?

### ISSUE THREAD

**Issue by tormath1** [sre-summercamp/sre-summercamp.github.io#21]
![photo_2022-08-01_12-47-10](https://user-images.githubusercontent.com/28657343/182132110-99ebeb90-6e11-4b80-973c-3b8b3acff050.jpg)

Even from a private navigation windows

**Comment by tormath1** [comment]
from a quick look `--primary` color is missing.

**Comment by tormath1** [comment]
aaah ok, it's not a bug - it's just based on the `prefers-color-scheme: dark|light`.
https://github.com/sre-summercamp/devfest-theme-hugo/blob/c9752a475ccd03619b5838bcde5974017eb818ff/src/styles/_root.scss#L114

@pabluk what do you think having the blue theme by default? The red is a bit hurting.

**Comment by pabluk** [comment]
> @pabluk what do you think having the blue theme by default? The red is a bit hurting.

Yes, no problem, I have no advice on colors, I'm very bad on design.

> https://github.com/sre-summercamp/devfest-theme-hugo/blob/c9752a475ccd03619b5838bcde5974017eb818ff/src/styles/_root.scss#L114

Exactly, if you wanna try other colors schema you just need to edit that line and this one https://github.com/sre-summercamp/devfest-theme-hugo/blob/c9752a475ccd03619b5838bcde5974017eb818ff/src/styles/_root.scss#L2

**Comment by tormath1** [comment]
> I'm very bad on design.

We're two then.

I feel that the blue one fits better with the water color:
![tmp 0KQ64kh3ZF](https://user-images.githubusercontent.com/28657343/182315920-4ab50d49-ac22-4cce-a3f0-2e9aec034007.png)

**Comment by pabluk** [comment]
> I feel that the blue one fits better with the water color:

Totally right! looks better with the sky and water :+1: Go for it!

**Comment by pabluk** [comment]
@tormath1 I think in this commit https://github.com/sre-summercamp/sre-summercamp.github.io/commit/85ae1f82a3128333080a33687f9bc32b532f6ed8 you also need to commit the generated file `static/theme.css` from the https://github.com/sre-summercamp/devfest-theme-hugo repo.
