### ISSUE TITLE
drop the "subscribe" section

### ISSUE THREAD

**Issue by tormath1** [sre-summercamp/sre-summercamp.github.io#25]
I don't think we'll have a newsletter or we can redirect directly to the twitter (it's the most up to date source of information)?

**Comment by pabluk** [comment]
Yes, I removed the references to the newsletter on these commits https://github.com/sre-summercamp/sre-summercamp.github.io/commit/eb64386c9139da6f627ee02ad6a20301d024d4ff https://github.com/sre-summercamp/sre-summercamp.github.io/commit/298d5947aa062ba67050ed4bcc97bf41131df28b.
I tried to replace them by a link to Twitter but those sections are built using a dedicated template for newsletters, so for the moment I just removed them.
