### ISSUE TITLE
FAQs

### ISSUE THREAD

**Issue by pabluk** [sre-summercamp/sre-summercamp.github.io#5]
Il faut écrire les FAQs pour l'event dans ces pages :

* Version en Français [content/faq/index.fr.md](content/faq/index.fr.md)
* Version en Anglais [content/faq/index.md](content/faq/index.md)

On peut s'inspirer de ces pages https://github.com/GDGToulouse/site-devfest-2019/blob/master/content/faq/index.fr.md et  https://github.com/GDGToulouse/site-devfest-2019/blob/master/content/faq/index.md

**Comment by tormath1** [comment]
Questions que j'ai en tête:
* quoi prendre? Une tenue pour être à l'aise en sport (baskets, shorts, etc.), un ordinateur et son plus grand sourire
* où loger? Les conférences auront lieux à Chambéry et les activités du côté d'Aix les bains, donc le logement est envisageable sur ces deux zones
* comment venir? Train depuis Lyon, Paris, etc.
* je ne fais pas de sport, je peux venir? Bien sûr, c'est avant tout un week-end convivial donc ce n'est pas week-end de sport - c'est ouvert à tous les niveaux!
* combien coûte l'événement? Une participation financière de Xe est demandée afin d'assurer les frais de restauration et des activités   
* je peux venir seulement à la moitié? Bien sûr, vous n'êtes pas séquestré - libre à vous d'assister à ce qu'il vous fait envie!
